import { Head as Helmet } from "vite-react-ssg";
import { Link } from "react-router-dom";
import { ArrowLeft, GitBranch, Workflow } from "lucide-react";
import { useTheme, FONT_DISPLAY, FONT_MONO } from "../../lib/theme.jsx";
import { Footer } from "../../components/Shared.jsx";

export function LifecycleFoundations() {
  const TOKENS = useTheme();
  return <div className="min-h-full flex flex-col"><Helmet><title>Lifecycle and Orchestration | FabricPrep</title><link rel="canonical" href="https://fabricprep.com/study-guides/shared/lifecycle-orchestration" /><meta name="description" content="Study Fabric lifecycle management, Git, deployment pipelines, and orchestration for DP-700 and DP-600." /></Helmet><main className="flex-1 px-6 sm:px-10 py-8 max-w-3xl mx-auto w-full"><Link to="/study-guides/shared" className="flex items-center gap-1 text-xs mb-6" style={{ color: TOKENS.inkMuted }}><ArrowLeft size={14} /> In-Depth Fabric Learning Path</Link><div className="text-xs uppercase mb-3 px-3 py-1 rounded-full inline-block" style={{ color: TOKENS.azure, letterSpacing: "0.14em", border: `1px solid ${TOKENS.azure}40`, fontFamily: FONT_MONO }}>Topic 07 · DP-700 · DP-600</div><h1 className="text-2xl sm:text-3xl font-semibold" style={{ color: TOKENS.ink, fontFamily: FONT_DISPLAY }}>Lifecycle Management and Orchestration</h1><p className="mt-3 text-sm" style={{ color: TOKENS.inkMuted }}>Connect source control, database projects, deployment pipelines, schedules, parameters, and operational workflows.</p><div className="grid sm:grid-cols-2 gap-4 mt-8">{[[GitBranch, "Lifecycle management", "Use Git, database projects, and deployment pipelines to promote controlled changes."], [Workflow, "Orchestration", "Use schedules, triggers, parameters, dynamic expressions, and dependencies to automate work."]].map(([Icon, title, body]) => <article key={title} className="rounded-xl p-5" style={{ background: TOKENS.panel, border: `1px solid ${TOKENS.panelBorder}` }}><Icon size={20} color={TOKENS.azure} className="mb-3" /><h2 className="text-base font-semibold mb-2" style={{ color: TOKENS.ink }}>{title}</h2><p className="text-sm" style={{ color: TOKENS.inkMuted }}>{body}</p></article>)}</div><div className="rounded-xl p-5 mt-6" style={{ background: `${TOKENS.amber}12`, border: `1px solid ${TOKENS.amber}40` }}><h2 className="text-base font-semibold mb-2" style={{ color: TOKENS.ink }}>Exam checklist</h2><p className="text-sm" style={{ color: TOKENS.inkMuted }}>Keep development, validation, approval, and production deployment separate. Use parameters and dynamic expressions to keep orchestration reusable.</p></div><div className="flex justify-start mt-8 pt-6" style={{ borderTop: `1px solid ${TOKENS.panelBorder}` }}><Link to="/study-guides/shared/security-governance" className="inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm" style={{ border: `1px solid ${TOKENS.panelBorder}`, color: TOKENS.ink }}><ArrowLeft size={14} /> Previous topic</Link></div></main><Footer /></div>;
}
