import { Head as Helmet } from "vite-react-ssg";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, Activity, Gauge } from "lucide-react";
import { useTheme, FONT_DISPLAY, FONT_MONO } from "../../lib/theme.jsx";
import { Footer } from "../../components/Shared.jsx";

export function MonitoringFoundations() {
  const TOKENS = useTheme();
  return <div className="min-h-full flex flex-col"><Helmet><title>Monitoring and Optimization | FabricPrep</title><link rel="canonical" href="https://fabricprep.com/study-guides/shared/monitoring-optimization" /><meta name="description" content="Study Microsoft Fabric monitoring, troubleshooting, and performance optimization for DP-700 and DP-600." /></Helmet><main className="flex-1 px-6 sm:px-10 py-8 max-w-3xl mx-auto w-full"><Link to="/study-guides/shared" className="flex items-center gap-1 text-xs mb-6" style={{ color: TOKENS.inkMuted }}><ArrowLeft size={14} /> In-Depth Fabric Learning Path</Link><div className="text-xs uppercase mb-3 px-3 py-1 rounded-full inline-block" style={{ color: TOKENS.azure, letterSpacing: "0.14em", border: `1px solid ${TOKENS.azure}40`, fontFamily: FONT_MONO }}>Topic 05 · DP-700 · DP-600</div><h1 className="text-2xl sm:text-3xl font-semibold" style={{ color: TOKENS.ink, fontFamily: FONT_DISPLAY }}>Monitor and Optimize Fabric Workloads</h1><p className="mt-3 text-sm" style={{ color: TOKENS.inkMuted }}>Build a repeatable approach for monitoring runs, identifying errors, and improving workload performance.</p><div className="grid sm:grid-cols-2 gap-4 mt-8">{[[Activity, "Monitor", "Review pipeline, Dataflow, notebook, Eventstream, and refresh activity."], [Gauge, "Optimize", "Reduce data scanned, fix small files, tune Spark, and improve query patterns."]].map(([Icon, title, body]) => <article key={title} className="rounded-xl p-5" style={{ background: TOKENS.panel, border: `1px solid ${TOKENS.panelBorder}` }}><Icon size={20} color={TOKENS.azure} className="mb-3" /><h2 className="text-base font-semibold mb-2" style={{ color: TOKENS.ink }}>{title}</h2><p className="text-sm" style={{ color: TOKENS.inkMuted }}>{body}</p></article>)}</div><div className="rounded-xl p-5 mt-6" style={{ background: `${TOKENS.amber}12`, border: `1px solid ${TOKENS.amber}40` }}><h2 className="text-base font-semibold mb-2" style={{ color: TOKENS.ink }}>Troubleshooting sequence</h2><ol className="text-sm space-y-2" style={{ color: TOKENS.inkMuted }}><li>1. Identify the failed item and run details.</li><li>2. Locate the failing activity, query, transformation, or shortcut.</li><li>3. Reduce the data scope and reproduce the issue.</li><li>4. Apply the smallest safe fix and validate the next run.</li></ol></div><div className="flex items-center justify-between gap-3 mt-8 pt-6" style={{ borderTop: `1px solid ${TOKENS.panelBorder}` }}><Link to="/study-guides/shared/warehouse-dimensional-modeling" className="inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm" style={{ border: `1px solid ${TOKENS.panelBorder}`, color: TOKENS.ink }}><ArrowLeft size={14} /> Previous topic</Link><Link to="/study-guides/shared/security-governance" className="inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm" style={{ background: TOKENS.azure, color: TOKENS.bgDeep }}>Next topic <ArrowRight size={14} /></Link></div></main><Footer /></div>;
}
